BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//$HOST//NONSGML v1.0//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
DTEND;TZID=$END
UID:$ID
LOCATION:$LOCATION
DESCRIPTION:$DESC
URL;VALUE=URI:$URL
SUMMARY:$SUMMARY
DTSTART;TZID=$START
END:VEVENT
END:VCALENDAR